version: "3.5"
services:
  spring-docker-demo:
    image: philrr16registry.azurecr.io/spring-docker-demo:latest
    build:
      context: .
    ports:
      - "8080:8080"
    volumes:
      - ./:/usr/src/mymaven
 #     - ${MAVEN_SETTINGS_FOLDER}:/root/.m2   # comment this line if you do not want to use you local maven settings or if you do not have a local maven installed
